### ISSUE TITLE
Weird behaviour when yanking

### ISSUE THREAD

**Issue by jcs090218** [purcell/whole-line-or-region#26]
Same issue with `emacs -q` with `GNU Emacs 29.3 (build 2, x86_64-w64-mingw32) of 2024-03-24`.

![ezgif-4-43418e0f0a](https://github.com/purcell/whole-line-or-region/assets/8685505/ba54e65c-4e20-45d0-925b-19c3ede8e357)

I was expecting the line should be (after yanking):

```
  name VARCHAR(1010) NOT NULL
```

And not (in the image):

```
10
  name VARCHAR(10) NOT NULL
```

### Step to reproduce

1. `emacs -q`
2. `eval` the following (in scratch buffer):

```
(require 'package)
(package-initialize)  ; assumed you have this package installed
```

3. Open a sql file with these lines:

```
CREATE TABLE account (
  name VARCHAR(10) NOT NULL
);
```

4. `M-x whole-line-or-region-local-mode`
5. Navigate to line 2 and `M-x whole-line-or-region-kill-region`
6. `M-x undo`
7. Select text `10` then `M-x kill-ring-save`
8. `M-x yank`

**Comment by m2ym** [comment]
I'm facing very same issue. After taking a quick look at the source code, I found that the issue is caused by the uncleared `yank-handler` text property. It seems to be easy to fix, but I wonder why `yank-handler' is needed actually.

**Comment by m2ym** [comment]
I'll work on that anyways when I have time.

**Comment by purcell** [comment]
IIRC, the `yank-handler` was so that the yank behaviour is overridden when `whole-line-or-region-mode` is enabled to handle the following case: if you copy the final line of a file, and there's no newline after it, then when it's yanked a newline should be added. Hopefully a test should fail if you disable the `yank-handler`, but a couple of tests are failing for me right now anyway. I'd appreciate a second opinion!
